config/routes.rb
Rails.application.routes.draw do

	resources :prestamos do
		resources :pagos
	end

	root 'static_pages#home'

	get '/monto', to: 'static_pages#monto'
  	get '/total', to: 'static_pages#total'

  	get '/index', to: 'prestamos#index'
  	get '/new', to: 'prestamos#new'
  	get '/edit', to: 'prestamos#edit'
  	get '/show', to: 'prestamos#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pago.rb
class Pago < ApplicationRecord
  belongs_to :prestamo

  validates :cuota, numericality: { only_integer: true }
  validates :cuota, numericality: { greater_than: 0 }

end

app/models/prestamo.rb
class Prestamo < ApplicationRecord

	TIPO = ['AUTO','VIVIENDA','PERSONAL']

	validates :monto, numericality: { only_integer: true }
	validates :monto, numericality: { greater_than: 5000 }


	has_many :pagos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pagos_controller.rb
class PagosController < ApplicationController

	def create
    	@prestamo = Prestamo.find(params[:prestamo_id])
    	@pago = @prestamo.pagos.create(pago_params)
    	redirect_to prestamo_path(@prestamo)
  	end
 	
  def destroy
    @prestamo = Prestamo.find(params[:prestamo_id])
		@pago = Pago.find(params[:id])
		@pago.destroy

		redirect_to prestamo_path(@prestamo)
	end
 	
  
  private
    def pago_params
      params.require(:pago).permit(:cuota)
    end
end

app/controllers/prestamos_controller.rb
class PrestamosController < ApplicationController

	def index
		@prestamos = Prestamo.all
  	end

	def show
  		@prestamo = Prestamo.find(params[:id])
  		@balance = @prestamo.pagos.sum("cuota")
  	end

	def new
		@prestamo = Prestamo.new
  	end

  	def edit
  		@prestamo = Prestamo.find(params[:id])
  	end

  	def create
  		@prestamo = Prestamo.new(prestamo_params)
 
    	if @prestamo.save
      		redirect_to @prestamo
    	else
      		render 'new'
    	end
  	end

    def destroy
      @destroyPago
    end

  	def update
  		@prestamo = Prestamo.find(params[:id])
 
    	if @prestamo.update(prestamo_params)
      		redirect_to @prestamo
    	else
      		render 'edit'
    	end
  	end


  	private
    def prestamo_params
      params.require(:prestamo).permit(:nombre, :monto, :tipo)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def home
		@count = Prestamo.count()
		@sum = Prestamo.sum("monto")
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pagos_helper.rb
module PagosHelper
end

app/helpers/prestamos_helper.rb
module PrestamosHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "Cooperativa", '#', id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Home", root_path  %></li>
				<li><%= link_to "Loans", index_path %></li>
			</ul>	
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Cooperativa</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>
  	<div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <% message %>
        </div>
      <% end %>
		  <%= yield %>
    </div>
  </body>

</html>

app/views/prestamos/edit.html.erb
<h1>Edit Loan</h1>
 
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for @prestamo do |f| %>
     
      <p>
        <%= f.label :nombre %><br>
        <%= f.text_field :nombre, class: "form-control"%>
      </p>
     
      <p>
        <%= f.label :monto %><br>
        <%= f.text_field :monto, class: "form-control" %>
      </p>

      <p>
        <%= f.label :tipo %><br>
        <%= f.collection_select :tipo, Prestamo::TIPO, :to_s, :to_s, :include_blank => true, class: "form-control" %>
      </p>
     
      <p>
        <%= f.submit "Create", class: "btn btn-primary"%>
      </p>
     
    <% end %>
     
    <h2><%= link_to 'Go Back', prestamos_path %></h2>

   </div>
</div>

app/views/prestamos/index.html.erb
<h1>Listing Loans</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <p>New loan? <%= link_to "Add one now!", new_path %></p>

    <table class=" table table-striped sortable">
      <tr>
        <th>Id</th>
        <th>Nombre Cliente</th>
        <th>Total Prestamo</th>
         <th colspan="3"></th>
      </tr>
     
      <% @prestamos.each do |prestamo| %>
        <tr>
          <td><%= link_to prestamo.id, prestamo_path(prestamo) %></td>
          <td><%= prestamo.nombre  %></td>
          <td>$<%= prestamo.monto %></td>
          <td><%= link_to 'Edit', edit_prestamo_path(prestamo) %></td>
        </tr>
      <% end %>
    </table>

    </div>
</div>

app/views/prestamos/new.html.erb
<h1>New Loan</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">

		<%= form_for @prestamo do |f| %>
			<%= f.label :nombre %>
			<%= f.text_field :nombre, class: "form-control" %>

			<%= f.label :monto %>
			<%= f.text_field :monto, class: "form-control" %>

			<%= f.label :tipo %>
			<%= f.collection_select :tipo, Prestamo::TIPO, :to_s, :to_s, :include_blank => true, class: "form-control" %>

			<%= f.submit "Create", class: "btn btn-primary" %>
		<% end %>

		<h2><%= link_to 'Go Back', prestamos_path %></h2>
		
	</div>
</div>

app/views/prestamos/show.html.erb
<div class="row">
  <div class="col-md-5 col-md-offset-3">

  	<h2>Data</h2>
  	<p>
	  <strong>Id:</strong>
	  <%= @prestamo.id %>
	</p>
	 
	<p>
	  <strong>Nombre:</strong>
	  <%= @prestamo.nombre %>
	</p>
	 
	<p>
	  <strong>Monto:</strong>
	  $<%= @prestamo.monto %>
	</p>

	<p>
	  <strong>Tipo:</strong>
	  <%= @prestamo.tipo %>
	</p>

	<p>
	  <strong>Created:</strong>
	  <%= @prestamo.created_at %>
	</p>

	<h2>Balance</h2>
 	<p><strong>You Owe:</strong>
    	$<%= @prestamo.monto - @balance %>
  	</p>

	<h2>Payments</h2>
		<%if @prestamo.pagos.first == nil%>
			<h2>
		   		AUN NO HA ABANODADO EL PRESTAMO
		  	</h2>

		<%else%>
			<% @prestamo.pagos.each do |pago| %>
			  	<p>
			    	<strong>Payed:</strong>
			    	$<%= pago.cuota %> <%= link_to "Delete", prestamo_pago_path(@prestamo, pago), data: {confirm: "Really delete this loan?"}, method: :delete %>
			  	</p>
		 
			 	 <p>
			    	<strong>Date payed:</strong>
			    	<%= pago.created_at %>
			  	</p>
			<% end %>

		<% end %>
 
	<h2>Add a payment:</h2>
	<%= form_for([@prestamo, @prestamo.pagos.build]) do |f| %>
  	<h2>
    	<%= f.label :cuota %><br>
    	<%= f.text_field :cuota %>
  	</h2>
  	<p>
    	<%= f.submit "Submit payment", class: "btn btn-primary" %>
  	</p>
	<% end %>

	<h2><%= link_to 'Go Back', prestamos_path %></h2>

   </div>
</div>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
	<h1>Bienvenido a nuestra Cooperativa</h1>

	<h3>Tu mejor opcion es con nosotros!</h3>
	<h2>Total de prestamos ofrecidos : <%= @count %></h2>
	<h2>Total de prestamos ofrecidos : $<%= @sum %></h2>

</div>